defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: Yong Peng
subtitle: Professor, Ph.D.

# left_side:
#   background_image: "./assets/images/left-background2.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"


# Side Menu Links
menu:
  - text: Portfolio
    link: /
    icon: ""

  - text: Research Projects 
    link: /sesearch-projects
    icon: ""

  - text: Entrusted Project
    link: /contact
    icon: ""

  - text: Teaching Projects
    link: /resume
    icon: ""

  - text: Awards and Honors
    link: /blog
    icon: ""
    
  - text: Publication
    link: /blog
    icon: ""

  - text: Patent
    link: /blog
    icon: ""

  - text: Student
    link: /blog
    icon: ""    

  - text: Academic Services
    link: /blog
    icon: ""




    
