defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: Yong Peng
subtitle: Professor, Ph.D.

# left_side:
#   background_image: "./assets/images/left-background.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"


# Side Menu Links
menu:
  - text: Portfolio
    link: /
    icon: ""

  - text: Research Projects 
    link: /sesearch-projects
    icon: ""

  - text: Entrusted Project
    link: /entrusted-project
    icon: ""

  - text: Teaching Projects
    link: /teaching-projects
    icon: ""

  - text: Awards and Honors
    link: /awards
    icon: ""
    
  - text: Publications
    link: /publications
    icon: ""

  - text: Patent
    link: /patent
    icon: ""

  - text: Student
    link: /student
    icon: ""    

  - text: Academic Services
    link: /academic-services
    icon: ""


# Socialmedia Icons
  - text: QQ:491743196
    icon: ""


    
