defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: Christian Ezeani
subtitle: Full-Stack Developer

# left_side:
#   background_image: "./assets/images/left-background.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"

footer:
  copyright_text: "&copy; Christian Ezeani"

# Side Menu Links
menu:
  - text: Portfolio
    link: /
    icon: ""

  - text: Research Projects 
    link: /skills-and-offers
    icon: ""

  - text: Entrusted Project
    link: /contact
    icon: ""

  - text: Teaching Projects
    link: /resume
    icon: ""

  - text: Awards and Honors
    link: /blog
    icon: ""
    
  - text: Publication
    link: /blog
    icon: ""

  - text: Patent
    link: /blog
    icon: ""

  - text: Student
    link: /blog
    icon: ""    

  - text: Academic Services
    link: /blog
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/christianezeani
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/christianezeani
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/christian.ezeani.cyb
    icon: fab fa-facebook-square

  - name: twitter
    link: https://www.twitter.com/christianezeani
    icon: fab fa-twitter


    
