remote_theme: christianezeani/panthera-jekyll

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Yong Peng
subtitle: Professor, Ph.D.

# left_side:
#   background_image: "./assets/images/left-background2.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"


# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: Blog Posts
    link: /blog
    icon: ""




    
